/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DengueLetalidade.java
 *
 * Created on 18/05/2010, 23:18:09
 */
package com.org.view;

import com.org.facade.SessionFacadeImpl;
import com.org.model.classes.Agravo;
import com.org.negocio.Configuracao;
import com.org.negocio.FiltroArquivo;
import com.org.service.DuplicidadeProcess;
import com.org.util.FileFilterUtils;
import com.org.util.SinanDateUtil;
import com.org.util.SinanUtil;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JProgressBar;

/**
 *
 * @author geraldo
 */
public class Duplicidade extends javax.swing.JPanel {
    
    List<String> listaArquivos = new ArrayList<String>();
    Map<String, String> parametros = new HashMap<String, String>();
    Date dtInicio;
    Date dtFim;

    /** Creates new form DengueLetalidade */
    public Duplicidade() {
        initComponents();
        //popula combo
        SinanUtil.populaComboAgravo(cbAgravo);
        
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCalcular = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        prbStatus = new javax.swing.JProgressBar();
        pnlArquivos2 = new javax.swing.JPanel();
        btnSelecionarArquivos2 = new javax.swing.JButton();
        btnLimparSelecao2 = new javax.swing.JButton();
        lblArquivosSelecionados2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dataInicio = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel8 = new javax.swing.JLabel();
        dataFim = new com.toedter.calendar.JDateChooser("dd/MM/yyyy", "##/##/#####", '_');
        jLabel9 = new javax.swing.JLabel();
        cbAgravo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        btCalcular.setLabel("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        pnlArquivos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecione os DBF "));

        btnSelecionarArquivos2.setText("Selecionar arquivos");
        btnSelecionarArquivos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarArquivos2ActionPerformed(evt);
            }
        });

        btnLimparSelecao2.setText("Limpar Seleção");
        btnLimparSelecao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSelecao2ActionPerformed(evt);
            }
        });

        lblArquivosSelecionados2.setText("Nenhum arquivo selecionado");
        lblArquivosSelecionados2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblArquivosSelecionados2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pnlArquivos2Layout = new javax.swing.GroupLayout(pnlArquivos2);
        pnlArquivos2.setLayout(pnlArquivos2Layout);
        pnlArquivos2Layout.setHorizontalGroup(
            pnlArquivos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(pnlArquivos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlArquivos2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSelecionarArquivos2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(btnLimparSelecao2)
                    .addContainerGap(181, Short.MAX_VALUE))
                .addComponent(lblArquivosSelecionados2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE))
        );
        pnlArquivos2Layout.setVerticalGroup(
            pnlArquivos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
            .addGroup(pnlArquivos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlArquivos2Layout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(pnlArquivos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSelecionarArquivos2)
                        .addComponent(btnLimparSelecao2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblArquivosSelecionados2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel7.setText("De"); // NOI18N

        dataInicio.getJCalendar().setWeekOfYearVisible(false);

        jLabel8.setText("até"); // NOI18N

        dataFim.getJCalendar().setWeekOfYearVisible(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Agravo:"); // NOI18N

        jLabel1.setText("Período:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlArquivos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btLimpar)
                        .addGap(150, 150, 150))))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAgravo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbAgravo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(6, 6, 6)))
                .addGap(43, 43, 43)
                .addComponent(pnlArquivos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean preencheuFormulario() {
//        if (cbUf.getSelectedItem().toString().equals("-- Selecione --")) {
//            Master.mensagem("Selecione a UF de residência");
//            return false;
//        }
        if (SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy").equals("")) {
            Master.mensagem("Informe o período inicial");
            return false;
        }
        if (SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy").equals("")) {
            Master.mensagem("Informe o período final");
            return false;
        }
//        if (Integer.parseInt(SinanDateUtil.dateToStringException(dataFim.getDate(), "dd/MM/yyyy").substring(6, 10)) > 2009){
//            Master.mensagem("Não é possível utilizar esse relatório para datas posteriores a 2009");
//            return false;
//        }
//        if (Integer.parseInt(SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy").substring(6, 10)) < 2007){
//            Master.mensagem("Não é possível utilizar esse relatório para datas anteriores a 2007");
//            return false;
//        }
        if(lblArquivosSelecionados2.getText().equals("Nenhum arquivo selecionado") && SessionFacadeImpl.isDbf()){
            Master.mensagem("Selecione um arquivo.");
            return false;
        }

        try {
            dtInicio = Agravo.converterParaData(SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy"));
            dtFim = Agravo.converterParaData(SinanDateUtil.dateToStringException(dataFim.getDate(), "dd/MM/yyyy"));
            if (dtFim.before(dtInicio)) {
                Master.mensagem("Data final deve ser maior que inicial");
                return false;
            }
        } catch (Exception e) {
            Master.mensagem("Data inválida");
            return false;
        }

        return true;
    }
    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        if (!this.preencheuFormulario()) {
            return;
        }
        
        parametros.put("dataInicio", SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy"));
        parametros.put("dataFim", SinanDateUtil.dateToStringException(dataFim.getDate(), "dd/MM/yyyy"));
        
        if(this.lblArquivosSelecionados2.getText() != null){
            String[] arquivos = this.lblArquivosSelecionados2.getText().split("\\|\\|");
            for (int k = 0; k < arquivos.length; k++) {
                String[] nome = arquivos[k].split(".DBF");
                listaArquivos.add(arquivos[k]);
            }
        }
        
        new DuplicidadeProcess(listaArquivos, parametros, prbStatus).execute();
        /*
        Map parametros = new HashMap();
        parametros.put("parArquivos", this.lblArquivosSelecionados2.getText());
        parametros.put("parVariosArquivos", "sim");
        session.setParametros(parametros);
        session.setDataFim(SinanDateUtil.dateToStringException(dataFim.getDate(), "dd/MM/yyyy"));
        session.setDataInicio(SinanDateUtil.dateToStringException(dataInicio.getDate(), "dd/MM/yyyy"));
        session.setJprogress(prbStatus);
        session.setRelatorio("DengueLetalidade");
        session.execute();
        */
}//GEN-LAST:event_btCalcularActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
//        cbMunicipio.removeAllItems();
//        cbRegional.removeAllItems();
//        cbUf.setSelectedIndex(0);
}//GEN-LAST:event_btLimparActionPerformed

    private String getBanco(){
        return SinanUtil.bancoAgravo(cbAgravo.getSelectedItem().toString());
    }
    
    
    private void btnSelecionarArquivos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarArquivos2ActionPerformed
        if(!cbAgravo.getSelectedItem().toString().equals("Selecione um Agravo")){
            
            JFileChooser fileopen = new JFileChooser();
            fileopen.removeChoosableFileFilter(fileopen.getAcceptAllFileFilter());
            fileopen.setMultiSelectionEnabled(false);
            //        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo DBF", "dbf");
            FiltroArquivo filtro = new FiltroArquivo();
            filtro.addExtension("dbf");
            filtro.setDescription("Arquivo DBF");
            if(cbAgravo.getSelectedItem().toString().equals("LEISHMANIOSE TEGUMENTAR AMERICANA")){
                filtro.addInicioNome("LTAN0");
                filtro.addInicioNome("LTAN1");
            }else if(cbAgravo.getSelectedItem().toString().equals("PARALISIA FLÁCIDA AGUDA/POLIOMIELITE")){
                filtro.addInicioNome("PFAN0");
                filtro.addInicioNome("PFAN1");
            }else{
                filtro.addInicioNome(getBanco());
            }

            //        fileopen.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fileopen.addChoosableFileFilter(filtro);

            File file2 = new File(new Configuracao().getCaminho());
            fileopen.setCurrentDirectory(file2);
            int ret = fileopen.showDialog(null, "Abrir DBF");
            if (ret == JFileChooser.APPROVE_OPTION) {
                File file = fileopen.getSelectedFile();
                if (lblArquivosSelecionados2.getText().equals("Nenhum arquivo selecionado")) {
                    lblArquivosSelecionados2.setText("");
                }
                
                lblArquivosSelecionados2.setText(lblArquivosSelecionados2.getText() + file.getName() + "||");
                
                Configuracao.setPropriedade("caminho", file.getParent() + "\\\\");
                parametros.put("diretorio", file.getParent() + "\\\\");
                    
                
                //quando for vários arquivos
                /*for (int i = 0; i < files.length; i++) {
                    //verifica se ja está selecionado
                    if (lblArquivosSelecionados2.getText().lastIndexOf(files[i].getName()) == -1) {
                        lblArquivosSelecionados2.setText(lblArquivosSelecionados2.getText() + files[i].getName() + "||");
                    }
                    Configuracao.setPropriedade("caminho", files[i].getParent() + "\\\\");
                    parametros.put("diretorio", files[i].getParent() + "\\\\");
                }*/

            }
        }else{
            SinanUtil.mensagem("Selecione um agravo");
        }
    }//GEN-LAST:event_btnSelecionarArquivos2ActionPerformed

    private void btnLimparSelecao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSelecao2ActionPerformed
        lblArquivosSelecionados2.setText("Nenhum arquivo selecionado");
}//GEN-LAST:event_btnLimparSelecao2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btnLimparSelecao2;
    private javax.swing.JButton btnSelecionarArquivos2;
    private javax.swing.JComboBox cbAgravo;
    private com.toedter.calendar.JDateChooser dataFim;
    private com.toedter.calendar.JDateChooser dataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblArquivosSelecionados2;
    private javax.swing.JPanel pnlArquivos2;
    private javax.swing.JProgressBar prbStatus;
    // End of variables declaration//GEN-END:variables
}
